[mypy]
files = app
python_version = 3.14
strict = true
ignore_missing_imports = true

[mypy-app.scheduler.cp_sat]
disallow_any_expr = false
disable_error_code = attr-defined

[mypy-app.scheduler.hierarchical]
disallow_any_expr = false
disable_error_code = attr-defined
