module.exports=[38273,a=>{"use strict";var b=a.i(7997);function c({children:a}){return(0,b.jsx)("html",{lang:"en",children:(0,b.jsx)("body",{className:"antialiased",children:a})})}a.s(["default",()=>c,"metadata",0,{title:"Create Next App",description:"Generated by create next app"}])}];

//# sourceMappingURL=app_pages%202_layout_tsx_756183df._.js.map